name: Secret Scan

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  leash-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: FasterApiWeb/leash-secrets/action@leash-secrets-v1.2.1
        with:
          scan-mode: all
          fail-on: critical
          severity: warning
